// EL DOM

// COMO FUNCIONA?
// TRANSFORMA CODIGO HTML
// ESTRUCTRUCTURA EN FORMA DE ARBOL
// INTERACCION DE JS CON EL HTML

// ESTRUCTURA DOM
// ETIQUETA => ELEMENTO
// DERIVACION INICIAL: HEAD Y BODY
// CADA ETIQUETA DERIVA DE UN "ETIQUETA PADRE"

// NODOS

// LA ESPECIFICACION COMPLETA DE DOM DEFINE 12 TIPOS DE NODOS, AUNQUE LOS MAS USADOS SON:

// WINDOW => LOS MAS USADOS
// DOCUMENT => LOS MAS USADOS
// ELEMENT => LOS MAS USADOS
// ATTR
// TEXT
// COMMENT

// WINDOW:
//REPRESENTA LA VENTANA DEL DOC DOM
// METODOS, PROPIEDADES Y EVENTOS DEL DOM

// DOCUMENT:
// NODO RAIZ
// DERIVAN TODOS LOS DEMAS NODOS

// ELEMENT:
// REPRESENTA CADA ETIQUETA DE XHTML
// UNICO NODO CON ATRIBUTOS
// UNICO NODO DEL QUE PUEDEN DERIVAR OTROS

// ATTR:
// UNO PARA CADA ETIQUETA HTML

//TEXT:
// CONTIENE EL TEXTO ENCERRADO EN CADA ETIQUETA

// COMMENT:
// REPRESENTA LOS COMENTARIOS

// METODOS BASICOS DEL DOM:

// LAS FORMAS MAS COMODAS Y POPULARES DE ACCEDER A UN NODO (ES DECIR, SELECCIONAR ELEMENTOS DE HTML EN JS) SON:

// getElementByld() => SELECCIONA POR ID

// getElementsByClassName() => SELECCIONA POR CLASE

// getElementByTagName() => SELECCIONA POR ETIQUETA

// querySelector() => ADENTRO DE LOS PARENTESIS SE UTILIZA UN SELECTOR DE CSS, # , . , NOMBRE DE ETIQUETA

// querySelectorAll() => ADENTRO DE LOS PARENTESIS SE UTILIZA UN SELECTOR DE CSS, # , . , NOMBRE DE ETIQUETA

// HTMLcollection vs Array

// LA PRINCIPAL DIFERENCIA ENTRE UN ARRAY Y UN HTMLcollection ES SU ORIGEN Y COMO SE ACCEDE A SUS ELEMENTOS.

// => UN ARRAY ES UN OBJETO NATIVO DE JAVSCRIPT QUE SE UTILIZA PARA ALMACENAR UNA COLLECION DE VALORES. SE PUEDEN ACCEDER A SUS ELEMENTOS MEDIANTE SU INDICE NUMERICO Y TIENE DISPONIBLES VARIOS METODOS PARA MANIPULAR SU CONTENIDO.

// => UN HTMLcollection ES UN OBJETO QUE SE UTILIZA PARA ALMACENAR UNA COLECCION DE ELEMENTOS DEL DOM (Dicument Object Model) QUE CUMPLEN CON UN CRITERIO ESPECIFICO. A DIFERENCIA DE LOS ARRAYS, LAS HTMLcollection NO TIENEN METODOS MANIPULACION (AUNQUE PUEDEN CONVERTIRSE FACILMENTE EN UNO UTILIZANDO EL SPREAD OPERATOR)
